# Generated by Django 4.0.4 on 2022-04-28 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='users',
        ),
        migrations.AddField(
            model_name='thread',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
