# Generated by Django 4.0.4 on 2022-04-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_chat', '0002_remove_thread_users_thread_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personalmessage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='thread_type',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='updated_at',
        ),
    ]
